import { Cocktail } from '../types';

export const cocktailRecipes: Omit<Cocktail, 'id'>[] = [
  {
    name: 'Margarita',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['tequila'],
    ingredients: [
      { name: 'Tequila', amount: '2 oz', isAlcohol: true, alcoholType: 'tequila' },
      { name: 'Triple Sec', amount: '1 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Fresh Lime Juice', amount: '1 oz', isAlcohol: false },
      { name: 'Salt', amount: 'for rim', isAlcohol: false },
    ],
    instructions: 'Rub lime around the rim of the glass and dip in salt. Shake tequila, triple sec, and lime juice with ice. Strain into the glass over fresh ice.',
    garnish: 'Lime wheel',
    glassType: 'Rocks glass',
  },
  {
    name: 'Mojito',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['rum'],
    ingredients: [
      { name: 'White Rum', amount: '2 oz', isAlcohol: true, alcoholType: 'rum' },
      { name: 'Fresh Lime Juice', amount: '1 oz', isAlcohol: false },
      { name: 'Sugar', amount: '2 tsp', isAlcohol: false },
      { name: 'Mint Leaves', amount: '8-10', isAlcohol: false },
      { name: 'Soda Water', amount: 'Top', isAlcohol: false },
    ],
    instructions: 'Muddle mint leaves with sugar and lime juice. Add rum and ice. Top with soda water and stir gently.',
    garnish: 'Mint sprig and lime wheel',
    glassType: 'Highball glass',
  },
  {
    name: 'Old Fashioned',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['whiskey'],
    ingredients: [
      { name: 'Bourbon or Rye', amount: '2 oz', isAlcohol: true, alcoholType: 'whiskey' },
      { name: 'Sugar Cube', amount: '1', isAlcohol: false },
      { name: 'Angostura Bitters', amount: '2-3 dashes', isAlcohol: false },
      { name: 'Water', amount: '1 tsp', isAlcohol: false },
    ],
    instructions: 'Muddle sugar cube with bitters and water. Add whiskey and ice. Stir until well-chilled.',
    garnish: 'Orange peel',
    glassType: 'Rocks glass',
  },
  {
    name: 'Martini',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['gin'],
    ingredients: [
      { name: 'Gin', amount: '2.5 oz', isAlcohol: true, alcoholType: 'gin' },
      { name: 'Dry Vermouth', amount: '0.5 oz', isAlcohol: true, alcoholType: 'liqueur' },
    ],
    instructions: 'Stir gin and vermouth with ice until well-chilled. Strain into a chilled martini glass.',
    garnish: 'Lemon twist or olive',
    glassType: 'Martini glass',
  },
  {
    name: 'Moscow Mule',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['vodka'],
    ingredients: [
      { name: 'Vodka', amount: '2 oz', isAlcohol: true, alcoholType: 'vodka' },
      { name: 'Fresh Lime Juice', amount: '0.5 oz', isAlcohol: false },
      { name: 'Ginger Beer', amount: '4-6 oz', isAlcohol: false },
    ],
    instructions: 'Fill copper mug with ice. Add vodka and lime juice. Top with ginger beer and stir gently.',
    garnish: 'Lime wheel',
    glassType: 'Copper mug',
  },
  {
    name: 'Daiquiri',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['rum'],
    ingredients: [
      { name: 'White Rum', amount: '2 oz', isAlcohol: true, alcoholType: 'rum' },
      { name: 'Fresh Lime Juice', amount: '1 oz', isAlcohol: false },
      { name: 'Simple Syrup', amount: '0.75 oz', isAlcohol: false },
    ],
    instructions: 'Shake all ingredients with ice. Strain into a chilled coupe glass.',
    garnish: 'Lime wheel',
    glassType: 'Coupe glass',
  },
  {
    name: 'Whiskey Sour',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['whiskey'],
    ingredients: [
      { name: 'Bourbon', amount: '2 oz', isAlcohol: true, alcoholType: 'whiskey' },
      { name: 'Fresh Lemon Juice', amount: '0.75 oz', isAlcohol: false },
      { name: 'Simple Syrup', amount: '0.5 oz', isAlcohol: false },
      { name: 'Egg White', amount: '1 (optional)', isAlcohol: false },
    ],
    instructions: 'Shake all ingredients vigorously with ice. Strain into a rocks glass over fresh ice.',
    garnish: 'Cherry and orange slice',
    glassType: 'Rocks glass',
  },
  {
    name: 'Cosmopolitan',
    category: 'Modern',
    difficulty: 'easy',
    alcoholTypes: ['vodka'],
    ingredients: [
      { name: 'Vodka', amount: '1.5 oz', isAlcohol: true, alcoholType: 'vodka' },
      { name: 'Cointreau', amount: '0.5 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Cranberry Juice', amount: '0.5 oz', isAlcohol: false },
      { name: 'Fresh Lime Juice', amount: '0.5 oz', isAlcohol: false },
    ],
    instructions: 'Shake all ingredients with ice. Strain into a chilled martini glass.',
    garnish: 'Lime wheel or orange peel',
    glassType: 'Martini glass',
  },
  {
    name: 'Mai Tai',
    category: 'Tiki',
    difficulty: 'medium',
    alcoholTypes: ['rum'],
    ingredients: [
      { name: 'Dark Rum', amount: '1 oz', isAlcohol: true, alcoholType: 'rum' },
      { name: 'White Rum', amount: '1 oz', isAlcohol: true, alcoholType: 'rum' },
      { name: 'Orange Curaçao', amount: '0.5 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Orgeat Syrup', amount: '0.5 oz', isAlcohol: false },
      { name: 'Fresh Lime Juice', amount: '1 oz', isAlcohol: false },
    ],
    instructions: 'Shake all ingredients with ice. Strain into a rocks glass over crushed ice.',
    garnish: 'Mint sprig and lime wheel',
    glassType: 'Rocks glass',
  },
  {
    name: 'Manhattan',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['whiskey'],
    ingredients: [
      { name: 'Rye Whiskey', amount: '2 oz', isAlcohol: true, alcoholType: 'whiskey' },
      { name: 'Sweet Vermouth', amount: '1 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Angostura Bitters', amount: '2 dashes', isAlcohol: false },
    ],
    instructions: 'Stir all ingredients with ice. Strain into a chilled coupe glass.',
    garnish: 'Cherry',
    glassType: 'Coupe glass',
  },
  {
    name: 'Negroni',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['gin'],
    ingredients: [
      { name: 'Gin', amount: '1 oz', isAlcohol: true, alcoholType: 'gin' },
      { name: 'Campari', amount: '1 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Sweet Vermouth', amount: '1 oz', isAlcohol: true, alcoholType: 'liqueur' },
    ],
    instructions: 'Stir all ingredients with ice. Strain into a rocks glass over fresh ice.',
    garnish: 'Orange peel',
    glassType: 'Rocks glass',
  },
  {
    name: 'Piña Colada',
    category: 'Tropical',
    difficulty: 'easy',
    alcoholTypes: ['rum'],
    ingredients: [
      { name: 'White Rum', amount: '2 oz', isAlcohol: true, alcoholType: 'rum' },
      { name: 'Coconut Cream', amount: '1.5 oz', isAlcohol: false },
      { name: 'Pineapple Juice', amount: '3 oz', isAlcohol: false },
    ],
    instructions: 'Blend all ingredients with ice until smooth. Pour into a hurricane glass.',
    garnish: 'Pineapple wedge and cherry',
    glassType: 'Hurricane glass',
  },
  {
    name: 'Aperol Spritz',
    category: 'Modern',
    difficulty: 'easy',
    alcoholTypes: ['liqueur'],
    ingredients: [
      { name: 'Aperol', amount: '3 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Prosecco', amount: '2 oz', isAlcohol: true, alcoholType: 'wine' },
      { name: 'Soda Water', amount: '1 oz', isAlcohol: false },
    ],
    instructions: 'Build in a wine glass filled with ice. Add Aperol, prosecco, then soda. Stir gently.',
    garnish: 'Orange slice',
    glassType: 'Wine glass',
  },
  {
    name: 'Tom Collins',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['gin'],
    ingredients: [
      { name: 'Gin', amount: '2 oz', isAlcohol: true, alcoholType: 'gin' },
      { name: 'Fresh Lemon Juice', amount: '1 oz', isAlcohol: false },
      { name: 'Simple Syrup', amount: '0.5 oz', isAlcohol: false },
      { name: 'Soda Water', amount: 'Top', isAlcohol: false },
    ],
    instructions: 'Shake gin, lemon juice, and syrup with ice. Strain into a Collins glass over ice. Top with soda.',
    garnish: 'Lemon wheel and cherry',
    glassType: 'Collins glass',
  },
  {
    name: 'Paloma',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['tequila'],
    ingredients: [
      { name: 'Tequila', amount: '2 oz', isAlcohol: true, alcoholType: 'tequila' },
      { name: 'Fresh Lime Juice', amount: '0.5 oz', isAlcohol: false },
      { name: 'Grapefruit Soda', amount: '4 oz', isAlcohol: false },
      { name: 'Salt', amount: 'for rim', isAlcohol: false },
    ],
    instructions: 'Salt the rim of a highball glass. Fill with ice. Add tequila and lime juice. Top with grapefruit soda.',
    garnish: 'Grapefruit wedge',
    glassType: 'Highball glass',
  },
  {
    name: 'Bloody Mary',
    category: 'Brunch',
    difficulty: 'medium',
    alcoholTypes: ['vodka'],
    ingredients: [
      { name: 'Vodka', amount: '1.5 oz', isAlcohol: true, alcoholType: 'vodka' },
      { name: 'Tomato Juice', amount: '3 oz', isAlcohol: false },
      { name: 'Lemon Juice', amount: '0.5 oz', isAlcohol: false },
      { name: 'Worcestershire Sauce', amount: '3 dashes', isAlcohol: false },
      { name: 'Hot Sauce', amount: '2-3 dashes', isAlcohol: false },
      { name: 'Salt and Pepper', amount: 'To taste', isAlcohol: false },
    ],
    instructions: 'Build in a highball glass over ice. Add all ingredients and stir well.',
    garnish: 'Celery stalk, lemon wedge, olives',
    glassType: 'Highball glass',
  },
  {
    name: 'Espresso Martini',
    category: 'Modern',
    difficulty: 'medium',
    alcoholTypes: ['vodka'],
    ingredients: [
      { name: 'Vodka', amount: '2 oz', isAlcohol: true, alcoholType: 'vodka' },
      { name: 'Coffee Liqueur', amount: '0.5 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Espresso', amount: '1 oz', isAlcohol: false },
      { name: 'Simple Syrup', amount: '0.25 oz', isAlcohol: false },
    ],
    instructions: 'Shake all ingredients vigorously with ice. Strain into a chilled martini glass.',
    garnish: 'Coffee beans',
    glassType: 'Martini glass',
  },
  {
    name: 'Long Island Iced Tea',
    category: 'Party',
    difficulty: 'medium',
    alcoholTypes: ['vodka', 'rum', 'gin', 'tequila'],
    ingredients: [
      { name: 'Vodka', amount: '0.5 oz', isAlcohol: true, alcoholType: 'vodka' },
      { name: 'Rum', amount: '0.5 oz', isAlcohol: true, alcoholType: 'rum' },
      { name: 'Gin', amount: '0.5 oz', isAlcohol: true, alcoholType: 'gin' },
      { name: 'Tequila', amount: '0.5 oz', isAlcohol: true, alcoholType: 'tequila' },
      { name: 'Triple Sec', amount: '0.5 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Lemon Juice', amount: '1 oz', isAlcohol: false },
      { name: 'Simple Syrup', amount: '0.5 oz', isAlcohol: false },
      { name: 'Cola', amount: 'Splash', isAlcohol: false },
    ],
    instructions: 'Shake all ingredients except cola with ice. Strain into a Collins glass over ice. Top with cola.',
    garnish: 'Lemon wedge',
    glassType: 'Collins glass',
  },
  {
    name: 'Dark and Stormy',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['rum'],
    ingredients: [
      { name: 'Dark Rum', amount: '2 oz', isAlcohol: true, alcoholType: 'rum' },
      { name: 'Ginger Beer', amount: '4 oz', isAlcohol: false },
      { name: 'Fresh Lime Juice', amount: '0.5 oz', isAlcohol: false },
    ],
    instructions: 'Fill a highball glass with ice. Add rum and lime juice. Top with ginger beer.',
    garnish: 'Lime wheel',
    glassType: 'Highball glass',
  },
  {
    name: 'French 75',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['gin'],
    ingredients: [
      { name: 'Gin', amount: '1.5 oz', isAlcohol: true, alcoholType: 'gin' },
      { name: 'Lemon Juice', amount: '0.5 oz', isAlcohol: false },
      { name: 'Simple Syrup', amount: '0.5 oz', isAlcohol: false },
      { name: 'Champagne', amount: 'Top', isAlcohol: true, alcoholType: 'wine' },
    ],
    instructions: 'Shake gin, lemon juice, and syrup with ice. Strain into a champagne flute. Top with champagne.',
    garnish: 'Lemon twist',
    glassType: 'Champagne flute',
  },
  {
    name: 'Caipirinha',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['other'],
    ingredients: [
      { name: 'Cachaça', amount: '2 oz', isAlcohol: true, alcoholType: 'other' },
      { name: 'Lime', amount: '1 whole', isAlcohol: false },
      { name: 'Sugar', amount: '2 tsp', isAlcohol: false },
    ],
    instructions: 'Cut lime into wedges and muddle with sugar. Add cachaça and ice. Stir well.',
    garnish: 'None',
    glassType: 'Rocks glass',
  },
  {
    name: 'Mint Julep',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['whiskey'],
    ingredients: [
      { name: 'Bourbon', amount: '2.5 oz', isAlcohol: true, alcoholType: 'whiskey' },
      { name: 'Simple Syrup', amount: '0.5 oz', isAlcohol: false },
      { name: 'Mint Leaves', amount: '8-10', isAlcohol: false },
    ],
    instructions: 'Muddle mint with syrup. Add bourbon and crushed ice. Stir until glass frosts.',
    garnish: 'Mint sprig',
    glassType: 'Julep cup',
  },
  {
    name: 'Sidecar',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['brandy'],
    ingredients: [
      { name: 'Cognac', amount: '2 oz', isAlcohol: true, alcoholType: 'brandy' },
      { name: 'Cointreau', amount: '0.75 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Lemon Juice', amount: '0.75 oz', isAlcohol: false },
    ],
    instructions: 'Shake all ingredients with ice. Strain into a sugar-rimmed coupe glass.',
    garnish: 'Lemon twist',
    glassType: 'Coupe glass',
  },
  {
    name: 'Aviation',
    category: 'Classic',
    difficulty: 'medium',
    alcoholTypes: ['gin'],
    ingredients: [
      { name: 'Gin', amount: '2 oz', isAlcohol: true, alcoholType: 'gin' },
      { name: 'Maraschino Liqueur', amount: '0.5 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Crème de Violette', amount: '0.25 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Lemon Juice', amount: '0.75 oz', isAlcohol: false },
    ],
    instructions: 'Shake all ingredients with ice. Strain into a chilled coupe glass.',
    garnish: 'Cherry',
    glassType: 'Coupe glass',
  },
  {
    name: 'Sazerac',
    category: 'Classic',
    difficulty: 'medium',
    alcoholTypes: ['whiskey'],
    ingredients: [
      { name: 'Rye Whiskey', amount: '2 oz', isAlcohol: true, alcoholType: 'whiskey' },
      { name: 'Absinthe', amount: 'Rinse', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Sugar Cube', amount: '1', isAlcohol: false },
      { name: 'Peychaud\'s Bitters', amount: '3 dashes', isAlcohol: false },
    ],
    instructions: 'Rinse glass with absinthe. Muddle sugar with bitters. Add whiskey and ice, stir. Strain into prepared glass.',
    garnish: 'Lemon peel',
    glassType: 'Rocks glass',
  },
  {
    name: 'Gimlet',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['gin'],
    ingredients: [
      { name: 'Gin', amount: '2.5 oz', isAlcohol: true, alcoholType: 'gin' },
      { name: 'Fresh Lime Juice', amount: '0.75 oz', isAlcohol: false },
      { name: 'Simple Syrup', amount: '0.5 oz', isAlcohol: false },
    ],
    instructions: 'Shake all ingredients with ice. Strain into a chilled coupe glass.',
    garnish: 'Lime wheel',
    glassType: 'Coupe glass',
  },
  {
    name: 'Amaretto Sour',
    category: 'Modern',
    difficulty: 'easy',
    alcoholTypes: ['liqueur'],
    ingredients: [
      { name: 'Amaretto', amount: '1.5 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Bourbon', amount: '0.75 oz', isAlcohol: true, alcoholType: 'whiskey' },
      { name: 'Lemon Juice', amount: '1 oz', isAlcohol: false },
      { name: 'Simple Syrup', amount: '0.5 oz', isAlcohol: false },
    ],
    instructions: 'Shake all ingredients with ice. Strain into a rocks glass over ice.',
    garnish: 'Cherry and orange slice',
    glassType: 'Rocks glass',
  },
  {
    name: 'Rum Punch',
    category: 'Tropical',
    difficulty: 'easy',
    alcoholTypes: ['rum'],
    ingredients: [
      { name: 'Dark Rum', amount: '1 oz', isAlcohol: true, alcoholType: 'rum' },
      { name: 'White Rum', amount: '1 oz', isAlcohol: true, alcoholType: 'rum' },
      { name: 'Orange Juice', amount: '2 oz', isAlcohol: false },
      { name: 'Pineapple Juice', amount: '2 oz', isAlcohol: false },
      { name: 'Grenadine', amount: '0.5 oz', isAlcohol: false },
    ],
    instructions: 'Shake all ingredients with ice. Strain into a hurricane glass over ice.',
    garnish: 'Orange slice and cherry',
    glassType: 'Hurricane glass',
  },
  {
    name: 'White Russian',
    category: 'Modern',
    difficulty: 'easy',
    alcoholTypes: ['vodka'],
    ingredients: [
      { name: 'Vodka', amount: '2 oz', isAlcohol: true, alcoholType: 'vodka' },
      { name: 'Coffee Liqueur', amount: '1 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Heavy Cream', amount: '1 oz', isAlcohol: false },
    ],
    instructions: 'Build in a rocks glass over ice. Add vodka and coffee liqueur. Float cream on top.',
    garnish: 'None',
    glassType: 'Rocks glass',
  },
  {
    name: 'Black Russian',
    category: 'Modern',
    difficulty: 'easy',
    alcoholTypes: ['vodka'],
    ingredients: [
      { name: 'Vodka', amount: '2 oz', isAlcohol: true, alcoholType: 'vodka' },
      { name: 'Coffee Liqueur', amount: '1 oz', isAlcohol: true, alcoholType: 'liqueur' },
    ],
    instructions: 'Build in a rocks glass over ice. Stir gently.',
    garnish: 'None',
    glassType: 'Rocks glass',
  },
  {
    name: 'Tequila Sunrise',
    category: 'Tropical',
    difficulty: 'easy',
    alcoholTypes: ['tequila'],
    ingredients: [
      { name: 'Tequila', amount: '2 oz', isAlcohol: true, alcoholType: 'tequila' },
      { name: 'Orange Juice', amount: '4 oz', isAlcohol: false },
      { name: 'Grenadine', amount: '0.5 oz', isAlcohol: false },
    ],
    instructions: 'Pour tequila and orange juice into a highball glass over ice. Slowly pour grenadine to create sunrise effect.',
    garnish: 'Orange slice and cherry',
    glassType: 'Highball glass',
  },
  {
    name: 'Boulevardier',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['whiskey'],
    ingredients: [
      { name: 'Bourbon', amount: '1.5 oz', isAlcohol: true, alcoholType: 'whiskey' },
      { name: 'Campari', amount: '1 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Sweet Vermouth', amount: '1 oz', isAlcohol: true, alcoholType: 'liqueur' },
    ],
    instructions: 'Stir all ingredients with ice. Strain into a rocks glass over a large ice cube.',
    garnish: 'Orange peel',
    glassType: 'Rocks glass',
  },
  {
    name: 'Zombie',
    category: 'Tiki',
    difficulty: 'hard',
    alcoholTypes: ['rum'],
    ingredients: [
      { name: 'White Rum', amount: '1 oz', isAlcohol: true, alcoholType: 'rum' },
      { name: 'Golden Rum', amount: '1 oz', isAlcohol: true, alcoholType: 'rum' },
      { name: 'Dark Rum', amount: '1 oz', isAlcohol: true, alcoholType: 'rum' },
      { name: 'Lime Juice', amount: '0.75 oz', isAlcohol: false },
      { name: 'Grapefruit Juice', amount: '1 oz', isAlcohol: false },
      { name: 'Cinnamon Syrup', amount: '0.5 oz', isAlcohol: false },
      { name: 'Grenadine', amount: '0.5 oz', isAlcohol: false },
    ],
    instructions: 'Shake all ingredients with ice. Strain into a tiki mug or hurricane glass over crushed ice.',
    garnish: 'Mint sprig and pineapple',
    glassType: 'Tiki mug',
  },
  {
    name: 'Bramble',
    category: 'Modern',
    difficulty: 'easy',
    alcoholTypes: ['gin'],
    ingredients: [
      { name: 'Gin', amount: '2 oz', isAlcohol: true, alcoholType: 'gin' },
      { name: 'Lemon Juice', amount: '1 oz', isAlcohol: false },
      { name: 'Simple Syrup', amount: '0.5 oz', isAlcohol: false },
      { name: 'Crème de Mûre', amount: '0.5 oz', isAlcohol: true, alcoholType: 'liqueur' },
    ],
    instructions: 'Shake gin, lemon juice, and syrup with ice. Strain into a rocks glass over crushed ice. Drizzle liqueur over top.',
    garnish: 'Blackberry and lemon slice',
    glassType: 'Rocks glass',
  },
  {
    name: 'Pisco Sour',
    category: 'Classic',
    difficulty: 'medium',
    alcoholTypes: ['brandy'],
    ingredients: [
      { name: 'Pisco', amount: '2 oz', isAlcohol: true, alcoholType: 'brandy' },
      { name: 'Lime Juice', amount: '1 oz', isAlcohol: false },
      { name: 'Simple Syrup', amount: '0.75 oz', isAlcohol: false },
      { name: 'Egg White', amount: '1', isAlcohol: false },
      { name: 'Angostura Bitters', amount: '3 dashes', isAlcohol: false },
    ],
    instructions: 'Shake all ingredients except bitters vigorously. Strain into a coupe glass. Dash bitters on foam.',
    garnish: 'Bitters pattern',
    glassType: 'Coupe glass',
  },
  {
    name: 'Hot Toddy',
    category: 'Hot',
    difficulty: 'easy',
    alcoholTypes: ['whiskey'],
    ingredients: [
      { name: 'Whiskey', amount: '2 oz', isAlcohol: true, alcoholType: 'whiskey' },
      { name: 'Honey', amount: '1 tbsp', isAlcohol: false },
      { name: 'Lemon Juice', amount: '0.5 oz', isAlcohol: false },
      { name: 'Hot Water', amount: '4 oz', isAlcohol: false },
    ],
    instructions: 'Add whiskey, honey, and lemon juice to a mug. Fill with hot water and stir.',
    garnish: 'Lemon wheel and cinnamon stick',
    glassType: 'Irish coffee mug',
  },
  {
    name: 'Irish Coffee',
    category: 'Hot',
    difficulty: 'easy',
    alcoholTypes: ['whiskey'],
    ingredients: [
      { name: 'Irish Whiskey', amount: '1.5 oz', isAlcohol: true, alcoholType: 'whiskey' },
      { name: 'Hot Coffee', amount: '6 oz', isAlcohol: false },
      { name: 'Brown Sugar', amount: '1 tsp', isAlcohol: false },
      { name: 'Heavy Cream', amount: '1 oz', isAlcohol: false },
    ],
    instructions: 'Add whiskey and sugar to mug. Fill with coffee. Float cream on top by pouring over back of spoon.',
    garnish: 'None',
    glassType: 'Irish coffee mug',
  },
  {
    name: 'Bellini',
    category: 'Modern',
    difficulty: 'easy',
    alcoholTypes: ['wine'],
    ingredients: [
      { name: 'Prosecco', amount: '3 oz', isAlcohol: true, alcoholType: 'wine' },
      { name: 'Peach Purée', amount: '1.5 oz', isAlcohol: false },
    ],
    instructions: 'Pour peach purée into champagne flute. Top with prosecco and stir gently.',
    garnish: 'Peach slice',
    glassType: 'Champagne flute',
  },
  {
    name: 'Corpse Reviver #2',
    category: 'Classic',
    difficulty: 'medium',
    alcoholTypes: ['gin'],
    ingredients: [
      { name: 'Gin', amount: '0.75 oz', isAlcohol: true, alcoholType: 'gin' },
      { name: 'Cointreau', amount: '0.75 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Lillet Blanc', amount: '0.75 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Lemon Juice', amount: '0.75 oz', isAlcohol: false },
      { name: 'Absinthe', amount: '1 dash', isAlcohol: true, alcoholType: 'liqueur' },
    ],
    instructions: 'Shake all ingredients with ice. Strain into a chilled coupe glass.',
    garnish: 'Orange peel',
    glassType: 'Coupe glass',
  },
  {
    name: 'Vesper',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['gin', 'vodka'],
    ingredients: [
      { name: 'Gin', amount: '2 oz', isAlcohol: true, alcoholType: 'gin' },
      { name: 'Vodka', amount: '1 oz', isAlcohol: true, alcoholType: 'vodka' },
      { name: 'Lillet Blanc', amount: '0.5 oz', isAlcohol: true, alcoholType: 'liqueur' },
    ],
    instructions: 'Shake all ingredients with ice. Strain into a chilled martini glass.',
    garnish: 'Lemon peel',
    glassType: 'Martini glass',
  },
  {
    name: 'Martinez',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['gin'],
    ingredients: [
      { name: 'Old Tom Gin', amount: '2 oz', isAlcohol: true, alcoholType: 'gin' },
      { name: 'Sweet Vermouth', amount: '1 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Maraschino Liqueur', amount: '0.25 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Angostura Bitters', amount: '2 dashes', isAlcohol: false },
    ],
    instructions: 'Stir all ingredients with ice. Strain into a chilled coupe glass.',
    garnish: 'Lemon twist',
    glassType: 'Coupe glass',
  },
  {
    name: 'Rusty Nail',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['whiskey'],
    ingredients: [
      { name: 'Scotch Whisky', amount: '1.5 oz', isAlcohol: true, alcoholType: 'whiskey' },
      { name: 'Drambuie', amount: '0.75 oz', isAlcohol: true, alcoholType: 'liqueur' },
    ],
    instructions: 'Build in a rocks glass over ice. Stir gently.',
    garnish: 'Lemon twist',
    glassType: 'Rocks glass',
  },
  {
    name: 'Blood and Sand',
    category: 'Classic',
    difficulty: 'medium',
    alcoholTypes: ['whiskey'],
    ingredients: [
      { name: 'Scotch Whisky', amount: '0.75 oz', isAlcohol: true, alcoholType: 'whiskey' },
      { name: 'Cherry Heering', amount: '0.75 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Sweet Vermouth', amount: '0.75 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Orange Juice', amount: '0.75 oz', isAlcohol: false },
    ],
    instructions: 'Shake all ingredients with ice. Strain into a chilled coupe glass.',
    garnish: 'Orange peel',
    glassType: 'Coupe glass',
  },
  {
    name: 'Clover Club',
    category: 'Classic',
    difficulty: 'medium',
    alcoholTypes: ['gin'],
    ingredients: [
      { name: 'Gin', amount: '2 oz', isAlcohol: true, alcoholType: 'gin' },
      { name: 'Raspberry Syrup', amount: '0.5 oz', isAlcohol: false },
      { name: 'Lemon Juice', amount: '0.5 oz', isAlcohol: false },
      { name: 'Egg White', amount: '1', isAlcohol: false },
    ],
    instructions: 'Dry shake all ingredients, then shake with ice. Strain into a chilled coupe glass.',
    garnish: 'Raspberry',
    glassType: 'Coupe glass',
  },
  {
    name: 'Singapore Sling',
    category: 'Classic',
    difficulty: 'hard',
    alcoholTypes: ['gin'],
    ingredients: [
      { name: 'Gin', amount: '1.5 oz', isAlcohol: true, alcoholType: 'gin' },
      { name: 'Cherry Heering', amount: '0.5 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Cointreau', amount: '0.25 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Benedictine', amount: '0.25 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Pineapple Juice', amount: '4 oz', isAlcohol: false },
      { name: 'Lime Juice', amount: '0.5 oz', isAlcohol: false },
      { name: 'Grenadine', amount: '0.5 oz', isAlcohol: false },
    ],
    instructions: 'Shake all ingredients with ice. Strain into a Collins glass over ice.',
    garnish: 'Pineapple and cherry',
    glassType: 'Collins glass',
  },
  {
    name: 'Penicillin',
    category: 'Modern',
    difficulty: 'medium',
    alcoholTypes: ['whiskey'],
    ingredients: [
      { name: 'Blended Scotch', amount: '2 oz', isAlcohol: true, alcoholType: 'whiskey' },
      { name: 'Lemon Juice', amount: '0.75 oz', isAlcohol: false },
      { name: 'Honey-Ginger Syrup', amount: '0.75 oz', isAlcohol: false },
      { name: 'Islay Scotch', amount: '0.25 oz', isAlcohol: true, alcoholType: 'whiskey' },
    ],
    instructions: 'Shake scotch, lemon juice, and syrup with ice. Strain into a rocks glass over ice. Float Islay scotch on top.',
    garnish: 'Candied ginger',
    glassType: 'Rocks glass',
  },
  {
    name: 'Sex on the Beach',
    category: 'Party',
    difficulty: 'easy',
    alcoholTypes: ['vodka'],
    ingredients: [
      { name: 'Vodka', amount: '1.5 oz', isAlcohol: true, alcoholType: 'vodka' },
      { name: 'Peach Schnapps', amount: '0.5 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Orange Juice', amount: '1.5 oz', isAlcohol: false },
      { name: 'Cranberry Juice', amount: '1.5 oz', isAlcohol: false },
    ],
    instructions: 'Shake all ingredients with ice. Strain into a highball glass over ice.',
    garnish: 'Orange slice',
    glassType: 'Highball glass',
  },
  {
    name: 'Blue Lagoon',
    category: 'Modern',
    difficulty: 'easy',
    alcoholTypes: ['vodka'],
    ingredients: [
      { name: 'Vodka', amount: '1.5 oz', isAlcohol: true, alcoholType: 'vodka' },
      { name: 'Blue Curaçao', amount: '1 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Lemonade', amount: '4 oz', isAlcohol: false },
    ],
    instructions: 'Build in a highball glass over ice. Stir gently.',
    garnish: 'Lemon wheel and cherry',
    glassType: 'Highball glass',
  },
  {
    name: 'Cuba Libre',
    category: 'Classic',
    difficulty: 'easy',
    alcoholTypes: ['rum'],
    ingredients: [
      { name: 'White Rum', amount: '2 oz', isAlcohol: true, alcoholType: 'rum' },
      { name: 'Fresh Lime Juice', amount: '0.5 oz', isAlcohol: false },
      { name: 'Cola', amount: '4 oz', isAlcohol: false },
    ],
    instructions: 'Fill a highball glass with ice. Add rum and lime juice. Top with cola and stir.',
    garnish: 'Lime wedge',
    glassType: 'Highball glass',
  },
  {
    name: 'Kamikaze',
    category: 'Party',
    difficulty: 'easy',
    alcoholTypes: ['vodka'],
    ingredients: [
      { name: 'Vodka', amount: '1.5 oz', isAlcohol: true, alcoholType: 'vodka' },
      { name: 'Triple Sec', amount: '1 oz', isAlcohol: true, alcoholType: 'liqueur' },
      { name: 'Lime Juice', amount: '1 oz', isAlcohol: false },
    ],
    instructions: 'Shake all ingredients with ice. Strain into a shot glass or coupe.',
    garnish: 'Lime wheel',
    glassType: 'Shot glass',
  },
];
